# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     filename: github-metrics/base.svg
      #     # Options
      #     user: ascotbe
      #     template: classic
      - name: Recently played games
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198331948304"
          plugin_steam_sections: player
          plugin_steam_games_limit: 10
          plugin_steam_recent_games_limit: 10
          plugin_steam_achievements_limit: 10
          plugin_steam_playtime_threshold: 10
